// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/adapters/outbound/grpc_pb/inventory.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockId       string                 `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetInventoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInventoryRequest) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *GetInventoryRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockId       string                 `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInventoryResponse) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *GetInventoryResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UseInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockId       string                 `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseInventoryRequest) Reset() {
	*x = UseInventoryRequest{}
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseInventoryRequest) ProtoMessage() {}

func (x *UseInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseInventoryRequest.ProtoReflect.Descriptor instead.
func (*UseInventoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *UseInventoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UseInventoryRequest) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *UseInventoryRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UseInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StockId       string                 `protobuf:"bytes,2,opt,name=stock_id,json=stockId,proto3" json:"stock_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseInventoryResponse) Reset() {
	*x = UseInventoryResponse{}
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseInventoryResponse) ProtoMessage() {}

func (x *UseInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseInventoryResponse.ProtoReflect.Descriptor instead.
func (*UseInventoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UseInventoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UseInventoryResponse) GetStockId() string {
	if x != nil {
		return x.StockId
	}
	return ""
}

func (x *UseInventoryResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_internal_adapters_outbound_grpc_pb_inventory_proto protoreflect.FileDescriptor

const file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDesc = "" +
	"\n" +
	"2internal/adapters/outbound/grpc_pb/inventory.proto\x12\agrpc_pb\"X\n" +
	"\x13GetInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstock_id\x18\x02 \x01(\tR\astockId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"Y\n" +
	"\x14GetInventoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstock_id\x18\x02 \x01(\tR\astockId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"X\n" +
	"\x13UseInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstock_id\x18\x02 \x01(\tR\astockId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"Y\n" +
	"\x14UseInventoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstock_id\x18\x02 \x01(\tR\astockId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount2\xac\x01\n" +
	"\x10InventoryService\x12K\n" +
	"\fGetInventory\x12\x1c.grpc_pb.GetInventoryRequest\x1a\x1d.grpc_pb.GetInventoryResponse\x12K\n" +
	"\fUseInventory\x12\x1c.grpc_pb.UseInventoryRequest\x1a\x1d.grpc_pb.UseInventoryResponseBDZBgithub.com/KKogaa/grpc-producer/internal/adapters/outbound/grpc_pbb\x06proto3"

var (
	file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescOnce sync.Once
	file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescData []byte
)

func file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescGZIP() []byte {
	file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescOnce.Do(func() {
		file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDesc)))
	})
	return file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDescData
}

var file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_adapters_outbound_grpc_pb_inventory_proto_goTypes = []any{
	(*GetInventoryRequest)(nil),  // 0: grpc_pb.GetInventoryRequest
	(*GetInventoryResponse)(nil), // 1: grpc_pb.GetInventoryResponse
	(*UseInventoryRequest)(nil),  // 2: grpc_pb.UseInventoryRequest
	(*UseInventoryResponse)(nil), // 3: grpc_pb.UseInventoryResponse
}
var file_internal_adapters_outbound_grpc_pb_inventory_proto_depIdxs = []int32{
	0, // 0: grpc_pb.InventoryService.GetInventory:input_type -> grpc_pb.GetInventoryRequest
	2, // 1: grpc_pb.InventoryService.UseInventory:input_type -> grpc_pb.UseInventoryRequest
	1, // 2: grpc_pb.InventoryService.GetInventory:output_type -> grpc_pb.GetInventoryResponse
	3, // 3: grpc_pb.InventoryService.UseInventory:output_type -> grpc_pb.UseInventoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_adapters_outbound_grpc_pb_inventory_proto_init() }
func file_internal_adapters_outbound_grpc_pb_inventory_proto_init() {
	if File_internal_adapters_outbound_grpc_pb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_outbound_grpc_pb_inventory_proto_goTypes,
		DependencyIndexes: file_internal_adapters_outbound_grpc_pb_inventory_proto_depIdxs,
		MessageInfos:      file_internal_adapters_outbound_grpc_pb_inventory_proto_msgTypes,
	}.Build()
	File_internal_adapters_outbound_grpc_pb_inventory_proto = out.File
	file_internal_adapters_outbound_grpc_pb_inventory_proto_goTypes = nil
	file_internal_adapters_outbound_grpc_pb_inventory_proto_depIdxs = nil
}
