// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/adapters/outbound/grpc_pb/test.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_internal_adapters_outbound_grpc_pb_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_test_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Test) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_internal_adapters_outbound_grpc_pb_test_proto protoreflect.FileDescriptor

const file_internal_adapters_outbound_grpc_pb_test_proto_rawDesc = "" +
	"\n" +
	"-internal/adapters/outbound/grpc_pb/test.proto\x12\agrpc_pb\",\n" +
	"\x04Test\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03ageBDZBgithub.com/KKogaa/grpc-producer/internal/adapters/outbound/grpc_pbb\x06proto3"

var (
	file_internal_adapters_outbound_grpc_pb_test_proto_rawDescOnce sync.Once
	file_internal_adapters_outbound_grpc_pb_test_proto_rawDescData []byte
)

func file_internal_adapters_outbound_grpc_pb_test_proto_rawDescGZIP() []byte {
	file_internal_adapters_outbound_grpc_pb_test_proto_rawDescOnce.Do(func() {
		file_internal_adapters_outbound_grpc_pb_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_test_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_test_proto_rawDesc)))
	})
	return file_internal_adapters_outbound_grpc_pb_test_proto_rawDescData
}

var file_internal_adapters_outbound_grpc_pb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_adapters_outbound_grpc_pb_test_proto_goTypes = []any{
	(*Test)(nil), // 0: grpc_pb.Test
}
var file_internal_adapters_outbound_grpc_pb_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_adapters_outbound_grpc_pb_test_proto_init() }
func file_internal_adapters_outbound_grpc_pb_test_proto_init() {
	if File_internal_adapters_outbound_grpc_pb_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_test_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_adapters_outbound_grpc_pb_test_proto_goTypes,
		DependencyIndexes: file_internal_adapters_outbound_grpc_pb_test_proto_depIdxs,
		MessageInfos:      file_internal_adapters_outbound_grpc_pb_test_proto_msgTypes,
	}.Build()
	File_internal_adapters_outbound_grpc_pb_test_proto = out.File
	file_internal_adapters_outbound_grpc_pb_test_proto_goTypes = nil
	file_internal_adapters_outbound_grpc_pb_test_proto_depIdxs = nil
}
