// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/adapters/outbound/grpc_pb/transaction.proto

package grpc_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTransactionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_internal_adapters_outbound_grpc_pb_transaction_proto protoreflect.FileDescriptor

const file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDesc = "" +
	"\n" +
	"4internal/adapters/outbound/grpc_pb/transaction.proto\x12\agrpc_pb\"[\n" +
	"\x18CreateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\\\n" +
	"\x19CreateTransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount2p\n" +
	"\x12TransactionService\x12Z\n" +
	"\x11CreateTransaction\x12!.grpc_pb.CreateTransactionRequest\x1a\".grpc_pb.CreateTransactionResponseBDZBgithub.com/KKogaa/grpc-producer/internal/adapters/outbound/grpc_pbb\x06proto3"

var (
	file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescOnce sync.Once
	file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescData []byte
)

func file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescGZIP() []byte {
	file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescOnce.Do(func() {
		file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDesc)))
	})
	return file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDescData
}

var file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_adapters_outbound_grpc_pb_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: grpc_pb.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 1: grpc_pb.CreateTransactionResponse
}
var file_internal_adapters_outbound_grpc_pb_transaction_proto_depIdxs = []int32{
	0, // 0: grpc_pb.TransactionService.CreateTransaction:input_type -> grpc_pb.CreateTransactionRequest
	1, // 1: grpc_pb.TransactionService.CreateTransaction:output_type -> grpc_pb.CreateTransactionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_adapters_outbound_grpc_pb_transaction_proto_init() }
func file_internal_adapters_outbound_grpc_pb_transaction_proto_init() {
	if File_internal_adapters_outbound_grpc_pb_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDesc), len(file_internal_adapters_outbound_grpc_pb_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_outbound_grpc_pb_transaction_proto_goTypes,
		DependencyIndexes: file_internal_adapters_outbound_grpc_pb_transaction_proto_depIdxs,
		MessageInfos:      file_internal_adapters_outbound_grpc_pb_transaction_proto_msgTypes,
	}.Build()
	File_internal_adapters_outbound_grpc_pb_transaction_proto = out.File
	file_internal_adapters_outbound_grpc_pb_transaction_proto_goTypes = nil
	file_internal_adapters_outbound_grpc_pb_transaction_proto_depIdxs = nil
}
